name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install DUB / LDC
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest
      - name: Build
        run: dub build
      - name: Dump smoke
        run: ./info --help && ./info --version
